[tasks.gen]
description = "generate .ts and .did"
workspace = false
command = "dfx"
args = ["generate"]
dependencies = ["did"]

[tasks.did]
description = "generate .did"
workspace = false
command = "cargo"
args= ["test"]