name: Push image for e2e test to registry
on:
  push:
    branches:
      - main
    paths:
      - 'e2e/docker/**'
jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./e2e/docker
          file: ./e2e/docker/Dockerfile
          push: true
          # NOTE: This tag is for the development phase
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dfx_hardhat_node:v0.1.0
