name: QA
on:
  pull_request:
  push:
    branches:
      - main
env:
  RUST_VERSION: 1.72.1
jobs:
  snapshot-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUST_VERSION }}
      - name: Install Rust
        run: |
          rustup update ${{ env.RUST_VERSION }} --no-self-update
          rustup default ${{ env.RUST_VERSION }}
          rustup component add rustfmt
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
      - name: Check rustfmt version
        run: |
           cargo fmt --version
           rustfmt --version
      - name: Check directory
        run: |
           pwd
           ls -l
           ls -l src
      - name: Format test resources
        working-directory: src/commands/tests/resources/template_project/src
        run: |
          cargo fmt
      - name: Run snapshot tests
        run: |
          RUST_TEST_TIME_UNIT=60000,300000 cargo +nightly test commands::tests -- -Zunstable-options --ensure-time
