name: Update crate version
on:
  workflow_dispatch:
    inputs:
      level_or_version:
        description: 'Parameter specifying update version, to use with `cargo release version` ex: `1.0.0`, `patch` etc'
        type: string
env:
  RUST_VERSION: 1.78.0
  DEFAULT_RELEASE_LEVEL: patch
  BASE_BRANCH_NAME: topic/bump-version
  CI_COMMIT_AUTHOR: github-actions
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUST_VERSION }}
      - name: Install Rust
        run: |
          rustup update ${{ env.RUST_VERSION }} --no-self-update
          rustup default ${{ env.RUST_VERSION }}
      - name: Install cargo-release
        run: cargo install cargo-release --locked
      - name: Run cargo release
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          cargo release version --execute --no-confirm ${{ github.event.inputs.level_or_version || env.DEFAULT_RELEASE_LEVEL }}
          PKG_VER=$(cargo metadata --format-version=1 --no-deps | jq ".packages[0].version" | tr -d '"')
          git checkout -b ${{ env.BASE_BRANCH_NAME }}-$PKG_VER
          git branch
          cargo release commit --execute --no-confirm
          git push -u origin HEAD
          gh pr create --fill
          gh pr merge --auto --merge
